# Generated by Django 4.2 on 2023-04-08 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id_phrase', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phrase', models.CharField(max_length=200)),
                ('translation', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='post_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phrases',
                'verbose_name_plural': 'Phrases',
                'ordering': ['-create_at'],
            },
        ),
    ]
